# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudio < Formula
  desc "Claude CLI proxy — manage AI agents with persistent sessions over your Claude subscription."
  homepage "https://github.com/bsantosio/claudio"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bsantosio/claudio/releases/download/v0.4.0/claudio_0.4.0_darwin_amd64.tar.gz"
      sha256 "4c3675c9d4562e8cbaea62dfcca4a3bf655c7c338b7a01ff6d3c76fe8ecc5259"

      define_method(:install) do
        bin.install "claudio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bsantosio/claudio/releases/download/v0.4.0/claudio_0.4.0_darwin_arm64.tar.gz"
      sha256 "0e7201b2dff244cf9d00383d60e4baefaa02f68d06cd48e41d7d61d14dc97930"

      define_method(:install) do
        bin.install "claudio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bsantosio/claudio/releases/download/v0.4.0/claudio_0.4.0_linux_amd64.tar.gz"
      sha256 "eb70827234c4a3593fecc857bf4db8ea4c8d3cf2dee531ca8d46bd8b045fc451"
      define_method(:install) do
        bin.install "claudio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bsantosio/claudio/releases/download/v0.4.0/claudio_0.4.0_linux_arm64.tar.gz"
      sha256 "a9c63573a248a2902c4c08f589751e14826a2c2f8d4bbf89829fc91f655c0557"
      define_method(:install) do
        bin.install "claudio"
      end
    end
  end
end
