# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claudio < Formula
  desc "Claude CLI proxy — manage AI agents with persistent sessions over your Claude subscription."
  homepage "https://github.com/bsantosio/claudio"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bsantosio/claudio/releases/download/v0.5.0/claudio_0.5.0_darwin_amd64.tar.gz"
      sha256 "b548ae15ed88567717549fe344353098ff854ea2a68294642fded5789a826fc8"

      define_method(:install) do
        bin.install "claudio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bsantosio/claudio/releases/download/v0.5.0/claudio_0.5.0_darwin_arm64.tar.gz"
      sha256 "09c0e755d1c5154a728ff37e1ffa60a2bc34ce537ef6821b2280823fe3b5ed8a"

      define_method(:install) do
        bin.install "claudio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bsantosio/claudio/releases/download/v0.5.0/claudio_0.5.0_linux_amd64.tar.gz"
      sha256 "6be719d9727d3de1faadc2b035843f2c159576103704f30074f77927c4b5bfd7"
      define_method(:install) do
        bin.install "claudio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bsantosio/claudio/releases/download/v0.5.0/claudio_0.5.0_linux_arm64.tar.gz"
      sha256 "1937e0dd19c9ca7ddef0bae13553d195ff0997e5ab55c110590948690b0e3506"
      define_method(:install) do
        bin.install "claudio"
      end
    end
  end
end
